# Generated by Django 6.0.4 on 2026-04-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='cases',
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(related_name='cases', to='cases.tag'),
        ),
    ]
